### ISSUE TITLE
Fix readme about encouraging transfering private keys

### ISSUE THREAD

**Issue by ilves** [TulevaEE/onboarding-service#85]
Sorry about this report, but just a friendly comment.

The read-me encourages reader to transfer private keys between machines and to local machine. In reality the most important principle about private keys is that the private key never leaves the machine.
I recommend to rework the deployment model or add notice that this is not recommended way.

**Comment by ErkoRisthein** [comment]
Thanks, valid point. Removed that part from the readme.
